stages:
  - structure
  - build_backend
  - publish_npm_package
  - build_frontend
  #- deploy

structure:
  stage: structure
  script:
    - '[ -d backend ] || exit 1'
    - '[ -d frontend ] || exit 1'
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
    - if: $CI_COMMIT_BRANCH == "spike/68-handle-openAPI-package-registry"


services:
  - name: docker:dind
    alias: dockerhost

variables:
  DOCKER_HOST: tcp://dockerhost:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  TESTCONTAINERS_HOST_OVERRIDE: dockerhost
  NPM_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/"
  NPM_SCOPE: "@dti-isin"

build_backend:
  stage: build_backend
  image:
    name: quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-21
    entrypoint: [""]
    docker:
      user: root
  script:
    - cd backend
    - chmod +x ./mvnw
    - ./mvnw clean verify -Pnative
  artifacts:
    paths:
      - backend/target/*-runner
      - backend/target/backend-api-client
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
    - if: $CI_COMMIT_BRANCH == "spike/68-handle-openAPI-package-registry"

publish_npm_package:
  stage: publish_npm_package
  image: node:22.14-alpine
  before_script:
    - echo "//gitlab-edu.supsi.ch/api/v4/projects/1051/packages/npm/:_authToken=${CI_JOB_TOKEN}" > backend/target/backend-api-client/.npmrc
    - echo "${NPM_SCOPE}:registry=${NPM_REGISTRY_URL}" >> .npmrc
  script:
    - cd backend/target/backend-api-client
    - npm install
    - npm publish --registry=${NPM_REGISTRY_URL}
  dependencies:
    - build_backend
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
    - if: $CI_COMMIT_BRANCH == "spike/68-handle-openAPI-package-registry"

build_frontend:
  stage: build_frontend
  image: node:22.14-alpine
  before_script:
    - echo "//gitlab-edu.supsi.ch/api/v4/projects/1051/packages/npm/:_authToken=${CI_JOB_TOKEN}" > frontend/.npmrc
    - echo "${NPM_SCOPE}:registry=${NPM_REGISTRY_URL}" >> frontend/.npmrc
  script:
    - cd frontend
    - npm install --no-audit
    - npm run build
  dependencies:
    - publish_npm_package
  artifacts:
    paths:
      - frontend/dist/
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
    - if: $CI_COMMIT_BRANCH == "spike/68-handle-openAPI-package-registry"

#deploy:
#  stage: deploy
#  script:
#    - docker-compose up -d
#  only:
#    - main