stages:
  - structure
  - build_backend
  - build_frontend
  #- deploy

structure:
  stage: structure
  script:
    - '[ -d backend ] || exit 1'
    - '[ -d frontend ] || exit 1'
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
    - if: $CI_COMMIT_BRANCH == "spike/51-native-image-quarkus"

services:
  - name: docker:dind
    alias: dockerhost

variables:
  DOCKER_HOST: tcp://dockerhost:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  TESTCONTAINERS_HOST_OVERRIDE: dockerhost

build_backend:
  stage: build_backend
  variables:
    AZURE_TENANT_ID: "3cadd1a7-ce2c-43b6-8986-2f1b472fab3b"  # SOSTITUIRE LE VARIABILI HARD-CODED E METTERLE SU GITLAB -> criptazione. Sol: QUARKUS_OIDC_TENANT_ID: "$OIDC_TENANT_ID"
    AZURE_CLIENT_ID: "527ea26f-be1b-428f-8d09-2849729fe4fe"
  image:
    name: quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-21
    entrypoint: [""]
  script:
    - cd backend
    #- mvn clean verify -Pnative -Dquarkus.oidc.enabled=false  #per test con oidc sistemare e aggiungere variabili ambiente per tenantID e clientID
    - ./mvnw clean verify -Pnative
  artifacts:
    paths:
      - backend/target/*-runner
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
    - if: $CI_COMMIT_BRANCH == "spike/51-native-image-quarkus"


build_frontend:
  stage: build_frontend
  image: node:22.14-alpine
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/dist/
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
    - if: $CI_COMMIT_BRANCH == "spike/51-native-image-quarkus"

#deploy:
#  stage: deploy
#  script:
#    - docker-compose up -d
#  only:
#    - main