variables:
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true

  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress
    --no-snapshot-updates
  #   -DinstallAtEnd=true
  #   -DdeployAtEnd=true


stages:
  - structure
  - build
  - test
  #- deploy

image: gitlab-edu.supsi.ch:5050/dti-isin/labingsw/common:maven3java17

cache:
  paths:
    - .m2/repository

structure:
  stage: structure
  script:
    - '[ -d backend ] || exit 1'
    - '[ -d frontend ] || exit 1'
    - '[ -d nginx ] || exit 1'
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
    - if: $CI_COMMIT_BRANCH == "configuration/initialization"

build_backend:
  stage: build
  script:
    - cd backend
    - mvn clean package
  artifacts:
    paths:
      - backend/target/*.jar
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
    - if: $CI_COMMIT_BRANCH == "configuration/initialization"

build_frontend:
  stage: build
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/dist/
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
    - if: $CI_COMMIT_BRANCH == "configuration/initialization"

#deploy:
#  stage: deploy
#  script:
#    - docker-compose up -d
#  only:
#    - main