version: '3.8'
services:
  backend:
    build: ./backend
    env_file:
      - backend/.env
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: mongodb://mongo:27017/myApp
    depends_on:
      - mongo
    networks:
      - app-network

  nginx:
    build: ./frontend
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
     - app-network

  mongo:
    image: mongo:latest
    container_name: mongoProd
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local
networks:
  app-network:
    driver: bridge