version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - backend/.env
    expose:
      - "8080"
    depends_on:
      - mongo
    networks:
      - internal

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: nginx:1.27.4-alpine
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - external
      - internal

  mongo:
    image: mongo:8.0.4
    container_name: mongoProd
    expose:
      - "27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - internal

volumes:
  mongo_data:
    driver: local

networks:
  internal:
    driver: bridge
    internal: true
  external:
    driver: bridge
    internal: false