version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - backend/.env
    expose:
      - "8080"
    depends_on:
      - mongo
    networks:
      - internal

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "80:80"
    depends_on:
      - backend
    networks:
      - external
      - internal

  mongo:
    image: mongo:8.0.4
    container_name: mongoProd
    restart: always
    expose:
      - "27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - internal

  ngrok:
    image: ngrok/ngrok:3.21.0-alpine
    container_name: ngrok-container
    restart: unless-stopped
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
      - NGROK_REGION=eu
    ports:
      - "4040:4040"
    command:
      - http
      - nginx:80
    networks:
      - external
    depends_on:
      - nginx

volumes:
  mongo_data:
    driver: local

networks:
  internal:
    driver: bridge
  external:
    driver: bridge
    internal: false