quarkus.oidc.auth-server-url=https://login.microsoftonline.com/${AZURE_TENANT_ID}/v2.0
quarkus.oidc.client-id=${AZURE_CLIENT_ID_BACKEND}
quarkus.oidc.application-type=service
quarkus.http.auth.permission.authenticated.paths=/api/secure/*
quarkus.http.auth.permission.authenticated.policy=authenticated
quarkus.oidc.token-store=jwt
quarkus.oidc.authentication=true
quarkus.oidc.token.issuer=https://login.microsoftonline.com/${AZURE_TENANT_ID}/v2.0

quarkus.http.cors=true

%dev.quarkus.http.cors.origins=http://localhost:3000
%prod.quarkus.http.cors.origins=${CORS_ORIGINS}

quarkus.http.cors.headers=accept, authorization, content-type, x-requested-with
quarkus.http.cors.methods=GET, POST, PUT, DELETE, OPTIONS
quarkus.http.cors.exposed-headers=*

quarkus.http.root-path=/api
quarkus.http.host=0.0.0.0