#Sostituire i vari Client, Tenant ID e Client Secret tramite file .env !!!
quarkus.oidc.auth-server-url=https://login.microsoftonline.com/3cadd1a7-ce2c-43b6-8986-2f1b472fab3b/v2.0
quarkus.oidc.client-id=e60732a1-5fd8-4c12-8a48-db860b8d4409
quarkus.oidc.credentials.secret=dck8Q~OHEwPbw3iUdFt1kmPicA_6G-LU4HkVtceK
quarkus.oidc.application-type=service
quarkus.http.auth.permission.authenticated.paths=/api/secure/*
quarkus.http.auth.permission.authenticated.policy=authenticated
#quarkus.oidc.authentication.redirect-path=/auth/redirect
#quarkus.oidc.token.issuer=any

# Abilita le politiche CORS
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:3000
quarkus.http.cors.headers=accept, authorization, content-type, x-requested-with
quarkus.http.cors.methods=GET, POST, PUT, DELETE, OPTIONS
quarkus.http.cors.exposed-headers=*

quarkus.http.root-path=/api