%dev.quarkus.mongodb.connection-string=mongodb://localhost:27017
%dev.quarkus.mongodb.database=myAppDev
%prod.quarkus.mongodb.connection-string=${MONGO_URI:mongodb+srv://root:1234@cluster0.nzhrv5c.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0}
%prod.quarkus.mongodb.database=myAppProd
%prod.quarkus.mongodb.tls=true
quarkus.hibernate-validator.fail-fast=true
quarkus.oidc.auth-server-url=https://login.microsoftonline.com/${AZURE_TENANT_ID:3cadd1a7-ce2c-43b6-8986-2f1b472fab3b}/v2.0
quarkus.oidc.client-id=${AZURE_CLIENT_ID:527ea26f-be1b-428f-8d09-2849729fe4fe}
quarkus.oidc.application-type=service
quarkus.http.auth.permission.authenticated.paths=/api/secure/*
quarkus.http.auth.permission.authenticated.policy=authenticated
quarkus.oidc.token.issuer=https://login.microsoftonline.com/${AZURE_TENANT_ID:3cadd1a7-ce2c-43b6-8986-2f1b472fab3b}/v2.0
quarkus.http.cors=true
%dev.quarkus.http.cors.origins=http://localhost:3000
%prod.quarkus.http.cors.origins=https://frontend-service-1031980811194.europe-west12.run.app
quarkus.http.cors.headers=accept, authorization, content-type, x-requested-with
quarkus.http.cors.methods=GET, POST, PUT, DELETE, OPTIONS
quarkus.http.cors.exposed-headers=*
quarkus.http.root-path=/api
quarkus.http.host=0.0.0.0
quarkus.http.port=${PORT:8080}
app.admin.names=Admin
app.admin.emails=admin${AZURE_DOMAIN_NAME:@testforprojectsupsi.onmicrosoft.com}
app.azure.tenant-id=${AZURE_TENANT_ID:3cadd1a7-ce2c-43b6-8986-2f1b472fab3b}
app.azure.client-id=${AZURE_CLIENT_ID:527ea26f-be1b-428f-8d09-2849729fe4fe}
app.azure.client-secret=${AZURE_SECRET:6.l8Q~9_cnbBGTCHKnniv3KAyF-BnQRQ7i~7oaxo}
app.azure.graph.scope=https://graph.microsoft.com/.default
quarkus.smallrye-openapi.path=/q/openapi
quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.store-schema-directory=target/classes/META-INF/resources
quarkus.mongodb.connection-timeout=60000
quarkus.mongodb.read-timeout=60000
quarkus.mongodb.max-connection-idle-time=60000
